### ISSUE TITLE
[Need Solve] 2.9.x全部API申明文件杂糅问题。

### ISSUE THREAD

**Issue by CreaklerFurry** [LiteLScript-Dev/HelperLib#22]
在DBSession类中，构造器 (constructor) 本应该有两种重载 Overload 
如文档：
![image](https://user-images.githubusercontent.com/77380048/217864446-759a9475-5e81-4fb9-9f79-c233db857225.png)
但在 "\dts\HelperLib-master\src\DataAPI\DataBase.d.ts" 中申明文件仅有
> constructor(type: 'sqlite3', params: DataBase_Params)
一种写法

这种方式不支持旧版本LLE (如 2.9.0)， 希望能在每一次的版本更新中发布一次 release 进行历史版本申明文件保存，谢谢。

**Comment by HuoHuas001** [comment]
已添加以string方式初始化DBSession的构造函数
您的`添加release历史版本申明文件保存`建议我们已经收到，我们会在以后的版本中加入
