### ISSUE TITLE
[A Problem] ...ConfigFile.write () 参数申明丢失

### ISSUE THREAD

**Issue by CreaklerFurry** [LiteLScript-Dev/HelperLib#23]
在 IniConfigFile 以及 JsonConfigFile中，共同方法: Wrtie() ,丢失参数 content: string
![image](https://user-images.githubusercontent.com/77380048/217908894-8a56e459-7d0e-422e-b77c-cf61ad60c787.png)

![image](https://user-images.githubusercontent.com/77380048/217908563-cda0c263-5cd7-4035-a012-d1b97388e73a.png)

**Comment by harry-xi** [comment]
fix in [9a0ab4c](https://github.com/LiteLScript-Dev/HelperLib/commit/9a0ab4c5f888484f32b18232ab433151f79a9478)
