### ISSUE TITLE
统一对引擎的整数类型的表示方式

### ISSUE THREAD

**Issue by harry-xi** [LiteLScript-Dev/HelperLib#8]
目前的类型声明文件里，对应文档`Integer`类型的属性/参数存在两中标记方式：`number` 和 `Integer` 
是否应统一为一个表现形式？
我本人倾向于统一为 `number` 并在对应的TsDoc注释内说明该参数应为整数/该值为整数

**Comment by lgc2333** [comment]
我目前在修订补全库docstring的时候把所有的Interger都换成了number的2022年9月14日 下午7:51，harryxi ***@***.***>写道：

目前的类型声明文件里，对应文档Integer类型的属性/参数存在两中标记方式：number 和 Integer

是否应统一为一个表现形式？

我本人倾向于统一为 number 并在对应的TsDoc注释内说明该参数应为整数/该值为整数

**Comment by harry-xi** [comment]
> 我目前在修订补全库docstring的时候把所有的Interger都换成了number的2022年9月14日 下午7:51，harryxi ***@***.***>写道： 目前的类型声明文件里，对应文档Integer类型的属性/参数存在两中标记方式：number 和 Integer 是否应统一为一个表现形式？ 我本人倾向于统一为 number 并在对应的TsDoc注释内说明该参数应为整数/该值为整数 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

既然如此，那就统一成number吧
